import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const colleges = [
  {
    name: "IIT Bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    fees: 250000,
    rating: 4.8,
    placementRate: 98.5,
    avgPackage: 2200000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    type: "Government",
    established: 1958,
    totalStudents: 10000,
    image: "",
    description: "IIT Bombay is one of India's premier engineering institutions, renowned for excellence in technical education and research.",
    accreditation: "NAAC A++",
    topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Amazon"],
  },
  {
    name: "IIT Delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    fees: 240000,
    rating: 4.8,
    placementRate: 97.8,
    avgPackage: 2100000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    type: "Government",
    established: 1961,
    totalStudents: 8500,
    image: "",
    description: "IIT Delhi is a public technical university located in Hauz Khas area of South Delhi.",
    accreditation: "NAAC A++",
    topRecruiters: ["Google", "Apple", "JP Morgan", "BCG", "Flipkart"],
  },
  {
    name: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 230000,
    rating: 4.9,
    placementRate: 98.2,
    avgPackage: 2300000,
    courses: ["B.Tech", "M.Tech", "PhD", "MBA"],
    type: "Government",
    established: 1959,
    totalStudents: 9000,
    image: "",
    description: "IIT Madras is consistently ranked as India's top engineering institution by NIRF.",
    accreditation: "NAAC A++",
    topRecruiters: ["Qualcomm", "Texas Instruments", "Microsoft", "Samsung", "Oracle"],
  },
  {
    name: "IIT Kanpur",
    location: "Kanpur, Uttar Pradesh",
    city: "Kanpur",
    state: "Uttar Pradesh",
    fees: 220000,
    rating: 4.8,
    placementRate: 97.0,
    avgPackage: 2000000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "M.Sc"],
    type: "Government",
    established: 1959,
    totalStudents: 8200,
    image: "",
    description: "IIT Kanpur is among India's top technical institutions, known for pioneering research and innovation.",
    accreditation: "NAAC A++",
    topRecruiters: ["Google", "Microsoft", "Facebook", "Amazon", "D.E. Shaw"],
  },
  {
    name: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    city: "Kharagpur",
    state: "West Bengal",
    fees: 210000,
    rating: 4.7,
    placementRate: 96.5,
    avgPackage: 1900000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD", "BArch"],
    type: "Government",
    established: 1951,
    totalStudents: 12000,
    image: "",
    description: "IIT Kharagpur is India's first IIT and remains one of the world's most respected engineering universities.",
    accreditation: "NAAC A++",
    topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "Schlumberger", "Samsung"],
  },
  {
    name: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    fees: 145000,
    rating: 4.5,
    placementRate: 92.0,
    avgPackage: 1200000,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
    type: "Government",
    established: 1964,
    totalStudents: 6000,
    image: "",
    description: "NIT Trichy is one of the top National Institutes of Technology in India.",
    accreditation: "NAAC A+",
    topRecruiters: ["TCS", "Infosys", "Wipro", "L&T", "Honeywell"],
  },
  {
    name: "NIT Warangal",
    location: "Warangal, Telangana",
    city: "Warangal",
    state: "Telangana",
    fees: 140000,
    rating: 4.4,
    placementRate: 91.0,
    avgPackage: 1100000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    type: "Government",
    established: 1959,
    totalStudents: 5500,
    image: "",
    description: "NIT Warangal is consistently ranked among the top NITs in India.",
    accreditation: "NAAC A+",
    topRecruiters: ["Microsoft", "Amazon", "Deloitte", "TCS", "Samsung"],
  },
  {
    name: "BITS Pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    fees: 500000,
    rating: 4.6,
    placementRate: 95.0,
    avgPackage: 1800000,
    courses: ["B.Tech", "B.Pharm", "MBA", "M.Tech", "M.Sc"],
    type: "Private",
    established: 1964,
    totalStudents: 7000,
    image: "",
    description: "BITS Pilani is a premier private engineering institution known for its industry-oriented curriculum.",
    accreditation: "NAAC A",
    topRecruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs", "Uber"],
  },
  {
    name: "IIIT Hyderabad",
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    fees: 300000,
    rating: 4.6,
    placementRate: 96.0,
    avgPackage: 1950000,
    courses: ["B.Tech", "M.Tech", "PhD", "MS"],
    type: "Private",
    established: 1998,
    totalStudents: 3000,
    image: "",
    description: "IIIT Hyderabad is a research university focusing on IT and related fields with strong industry ties.",
    accreditation: "NAAC A",
    topRecruiters: ["Google", "Microsoft", "Adobe", "Qualcomm", "Amazon"],
  },
  {
    name: "IIIT Bangalore",
    location: "Bengaluru, Karnataka",
    city: "Bengaluru",
    state: "Karnataka",
    fees: 320000,
    rating: 4.5,
    placementRate: 94.0,
    avgPackage: 1700000,
    courses: ["B.Tech", "M.Tech", "PhD", "MS"],
    type: "Private",
    established: 1999,
    totalStudents: 2500,
    image: "",
    description: "IIIT Bangalore is an autonomous institution focused on IT research and education.",
    accreditation: "NAAC A",
    topRecruiters: ["Google", "Amazon", "Flipkart", "Adobe", "Oracle"],
  },
  {
    name: "VIT Vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    fees: 350000,
    rating: 4.2,
    placementRate: 88.0,
    avgPackage: 950000,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "B.Sc"],
    type: "Private",
    established: 1984,
    totalStudents: 35000,
    image: "",
    description: "VIT Vellore is one of the largest private universities in India with excellent placement records.",
    accreditation: "NAAC A++",
    topRecruiters: ["TCS", "Wipro", "Infosys", "HCL", "Cognizant"],
  },
  {
    name: "Delhi Technological University",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    fees: 180000,
    rating: 4.3,
    placementRate: 89.0,
    avgPackage: 1100000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    type: "Government",
    established: 1941,
    totalStudents: 8000,
    image: "",
    description: "DTU is one of Delhi's premier technical universities, formerly known as Delhi College of Engineering.",
    accreditation: "NAAC A",
    topRecruiters: ["Microsoft", "Amazon", "Samsung", "Deloitte", "Capgemini"],
  },
  {
    name: "Jadavpur University",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    fees: 50000,
    rating: 4.4,
    placementRate: 85.0,
    avgPackage: 900000,
    courses: ["B.Tech", "BE", "M.Tech", "MBA", "PhD"],
    type: "Government",
    established: 1955,
    totalStudents: 7500,
    image: "",
    description: "Jadavpur University is a public university in Kolkata, highly regarded for engineering and sciences.",
    accreditation: "NAAC A++",
    topRecruiters: ["TCS", "Wipro", "IBM", "Tata Steel", "Infosys"],
  },
  {
    name: "Manipal Institute of Technology",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    fees: 420000,
    rating: 4.1,
    placementRate: 82.0,
    avgPackage: 800000,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "B.Pharm"],
    type: "Private",
    established: 1957,
    totalStudents: 14000,
    image: "",
    description: "MIT Manipal is one of India's oldest and most respected private engineering colleges.",
    accreditation: "NAAC A+",
    topRecruiters: ["Infosys", "Wipro", "TCS", "Accenture", "Cisco"],
  },
  {
    name: "Anna University",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 75000,
    rating: 4.2,
    placementRate: 80.0,
    avgPackage: 750000,
    courses: ["B.Tech", "BE", "M.Tech", "MBA", "PhD"],
    type: "Government",
    established: 1978,
    totalStudents: 12000,
    image: "",
    description: "Anna University is a technical university in Tamil Nadu, one of the largest in the country.",
    accreditation: "NAAC A+",
    topRecruiters: ["TCS", "CTS", "Infosys", "Wipro", "HCL"],
  },
  {
    name: "SRM Institute of Science and Technology",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    fees: 380000,
    rating: 4.0,
    placementRate: 78.0,
    avgPackage: 700000,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "PhD"],
    type: "Private",
    established: 1985,
    totalStudents: 52000,
    image: "",
    description: "SRM IST is one of the top private universities in India with a large campus and diverse programs.",
    accreditation: "NAAC A++",
    topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "Capgemini"],
  },
  {
    name: "COEP Technological University",
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    fees: 110000,
    rating: 4.3,
    placementRate: 87.0,
    avgPackage: 950000,
    courses: ["B.Tech", "BE", "M.Tech", "MBA"],
    type: "Government",
    established: 1854,
    totalStudents: 4000,
    image: "",
    description: "COEP is one of India's oldest and most prestigious engineering colleges.",
    accreditation: "NAAC A+",
    topRecruiters: ["Mercedes-Benz", "Cummins", "Infosys", "TCS", "Bosch"],
  },
  {
    name: "Thapar Institute of Engineering",
    location: "Patiala, Punjab",
    city: "Patiala",
    state: "Punjab",
    fees: 440000,
    rating: 4.1,
    placementRate: 83.0,
    avgPackage: 900000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    type: "Private",
    established: 1956,
    totalStudents: 10000,
    image: "",
    description: "Thapar Institute is a premier private engineering university with strong industry collaborations.",
    accreditation: "NAAC A",
    topRecruiters: ["Infosys", "TCS", "Amazon", "Deloitte", "HCL"],
  },
  {
    name: "PSG College of Technology",
    location: "Coimbatore, Tamil Nadu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    fees: 120000,
    rating: 4.2,
    placementRate: 84.0,
    avgPackage: 800000,
    courses: ["B.Tech", "BE", "M.Tech", "MBA", "MCA"],
    type: "Private",
    established: 1951,
    totalStudents: 8000,
    image: "",
    description: "PSG College of Technology is a renowned autonomous institution in Coimbatore.",
    accreditation: "NAAC A+",
    topRecruiters: ["BOSCH", "TCS", "Cognizant", "Wipro", "L&T"],
  },
  {
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    fees: 400000,
    rating: 3.8,
    placementRate: 72.0,
    avgPackage: 600000,
    courses: ["B.Tech", "MBA", "BBA", "LLB", "B.Sc", "MCA"],
    type: "Private",
    established: 2005,
    totalStudents: 125000,
    image: "",
    description: "Amity University is one of India's largest private universities offering diverse programs.",
    accreditation: "NAAC A+",
    topRecruiters: ["TCS", "Wipro", "HCL", "Cognizant", "Infosys"],
  },
];

async function main() {
  console.log('Seeding database...');

  // Clear existing data first
  await prisma.college.deleteMany();
  console.log('Cleared existing colleges');

  // Insert one by one
  for (const college of colleges) {
    await prisma.college.create({ data: college });
  }

  console.log(`✅ Seeded ${colleges.length} colleges successfully`);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });